const EX_ROWS = [
 ['Kind','Table','Name','Type','Folder','Flags','Description','Expression','ToTable','ToColumn','Storage','Source'],
 ['Table','Sales','Sales','','','','One row per order line.','','','','Import',''],
 ['Table','Customer','Customer','','','','','','','','Import',''],
 ['Table','Product','Product','','','','','','','','Import',''],
 ['Table','Date','Date','Time','','','','','','','Import',''],
 ['Table','_Measures','_Measures','','','','','','','','Import',''],
 ['Column','Sales','Net Amount','Decimal','','','Invoiced amount after discounts, before tax.','','','','',''],
 ['Column','Sales','Quantity','Int64','','','','','','','',''],
 ['Column','Sales','ORD_STS_CD','String','','','','','','','',''],
 ['Column','Sales','Order ID','String','','','','','','','',''],
 ['Column','Sales','Channel','String','','','','','','','',''],
 ['Column','Sales','CustomerKey','Int64','','hidden','','','','','',''],
 ['Column','Sales','ProductKey','Int64','','hidden','','','','','',''],
 ['Column','Sales','Order Date','DateTime','','hidden','','','','','',''],
 ['Column','Customer','CustomerKey','Int64','','hidden key','','','','','',''],
 ['Column','Customer','Name','String','','','','','','','',''],
 ['Column','Customer','Region','String','','','','','','','',''],
 ['Column','Customer','Segment','String','','','','','','','',''],
 ['Column','Product','ProductKey','Int64','','hidden key','','','','','',''],
 ['Column','Product','Name','String','','','','','','','',''],
 ['Column','Product','Category','String','','','','','','','',''],
 ['Column','Date','Date','DateTime','','key','','','','','',''],
 ['Column','Date','Fiscal Year','String','','','Fiscal year starts 1 February.','','','','',''],
 ['Column','Date','Month','String','','','','','','','',''],
 ['Measure','_Measures','Total Sales','\\$#,0','Core','','Net sales after discounts, before tax.','SUM ( Sales[Net Amount] )','','','',''],
 ['Measure','_Measures','Order Count','#,0','Core','','','DISTINCTCOUNT ( Sales[Order ID] )','','','',''],
 ['Measure','_Measures','Gross Margin %','0.0%','Profit','','','DIVIDE ( [Total Sales] - [Total Cost], [Total Sales] )','','','',''],
 ['Measure','_Measures','Return Rate %','0.0%','Quality','','',"DIVIDE ( CALCULATE ( SUM ( Sales[Quantity] ), Sales[ORD_STS_CD] = \"R\" ), SUM ( Sales[Quantity] ) )",'','','',''],
 ['Measure','_Measures','Sales Card HTML','','Visuals','','','"<div>" & [Total Sales] & "</div>"','','','',''],
 ['Relationship','Sales','CustomerKey','Many:One','','OneDirection','','','Customer','CustomerKey','',''],
 ['Relationship','Sales','ProductKey','Many:One','','OneDirection','','','Product','ProductKey','',''],
 ['Relationship','Sales','Order Date','Many:One','','OneDirection','','','Date','Date','','']
];
const EX_MODEL = EX_ROWS.map(r => r.join('\t')).join('\n');
