const FP_EX_ROWS = [
 ['Kind','Table','Name','Type','Folder','Flags','Description','Expression','ToTable','ToColumn','Storage','Source'],
 ['Table','Sales','Sales','','','','One row per order line.','','','','Import',''],
 ['Table','Customer','Customer','','','','','','','','Import',''],
 ['Table','Product','Product','','','','','','','','Import',''],
 ['Table','Date','Date','Time','','','','','','','Import',''],
 ['Table','_Measures','_Measures','','','','','','','','Import',''],
 ['Column','Sales','Net Amount','Decimal','','','','','','','',''],
 ['Column','Sales','Quantity','Int64','','','','','','','',''],
 ['Column','Sales','Channel','String','','','','','','','',''],
 ['Column','Sales','CustomerKey','Int64','','hidden','','','','','',''],
 ['Column','Sales','ProductKey','Int64','','hidden','','','','','',''],
 ['Column','Sales','Order Date','DateTime','','hidden','','','','','',''],
 ['Column','Customer','CustomerKey','Int64','','hidden key','','','','','',''],
 ['Column','Customer','Customer Name','String','','','','','','','',''],
 ['Column','Customer','Region','String','','','','','','','',''],
 ['Column','Customer','Segment','String','','','','','','','',''],
 ['Column','Product','ProductKey','Int64','','hidden key','','','','','',''],
 ['Column','Product','Product Name','String','','','','','','','',''],
 ['Column','Product','Category','String','','','','','','','',''],
 ['Column','Date','Date','DateTime','','key','','','','','',''],
 ['Column','Date','Year','Int64','','','','','','','',''],
 ['Column','Date','Month','String','','','','','','','',''],
 ['Measure','_Measures','Total Sales','\\$#,0','Revenue','','','SUM ( Sales[Net Amount] )','','','',''],
 ['Measure','_Measures','Sales LY','\\$#,0','Revenue','','','CALCULATE ( [Total Sales], SAMEPERIODLASTYEAR ( \'Date\'[Date] ) )','','','',''],
 ['Measure','_Measures','Sales YoY %','0.0%','Revenue','','','DIVIDE ( [Total Sales] - [Sales LY], [Sales LY] )','','','',''],
 ['Measure','_Measures','Total Cost','\\$#,0','Profit','','','SUM ( Sales[Total Cost] )','','','',''],
 ['Measure','_Measures','Gross Margin','\\$#,0','Profit','','','[Total Sales] - [Total Cost]','','','',''],
 ['Measure','_Measures','Gross Margin %','0.0%','Profit','','','DIVIDE ( [Gross Margin], [Total Sales] )','','','',''],
 ['Measure','_Measures','Order Count','#,0','Volume','','','DISTINCTCOUNT ( Sales[Order ID] )','','','',''],
 ['Measure','_Measures','Units Sold','#,0','Volume','','','SUM ( Sales[Quantity] )','','','',''],
 ['Measure','_Measures','Avg Order Value','\\$#,0.00','Volume','','','DIVIDE ( [Total Sales], [Order Count] )','','','',''],
 ['Relationship','Sales','CustomerKey','Many:One','','OneDirection','','','Customer','CustomerKey','',''],
 ['Relationship','Sales','ProductKey','Many:One','','OneDirection','','','Product','ProductKey','',''],
 ['Relationship','Sales','Order Date','Many:One','','OneDirection','','','Date','Date','','']
];
const FP_EX_MODEL = FP_EX_ROWS.map(r => r.join('\t')).join('\n');
const FP_EX_ITEMS = [
 { kind: 'measure', table: '_Measures', name: 'Total Sales', label: 'Sales', group: 'Revenue' },
 { kind: 'measure', table: '_Measures', name: 'Sales YoY %', label: 'Sales growth', group: 'Revenue' },
 { kind: 'measure', table: '_Measures', name: 'Gross Margin', label: 'Margin', group: 'Profit' },
 { kind: 'measure', table: '_Measures', name: 'Gross Margin %', label: 'Margin %', group: 'Profit' },
 { kind: 'measure', table: '_Measures', name: 'Order Count', label: 'Orders', group: 'Volume' }
];
