const PW_EX = {
  goal: 'Sales lines from the data warehouse, from 1 January 2023 onwards, without cancelled orders. Keep the order number, order date, customer key, product key, quantity and net amount. Add a Year column from the order date, and bring in the customer’s region from the Customers query.',
  start: 'new', source: 'sql', sourceDetail: 'ServerName / DatabaseName parameters, view dbo.vSalesLines',
  columns: 'OrderNumber\tOrderDate\tCustomerKey\tProductKey\tQuantity\tNetAmount\tStatus\tCreatedBy\n' +
    'SO-10001\t2023-01-04\t1042\t311\t2\t129.90\tShipped\tetl\n' +
    'SO-10002\t2023-01-04\t1188\t57\t1\t64.50\tCancelled\tetl\n' +
    'SO-10003\t2023-01-05\t1042\t98\t5\t402.00\tShipped\tetl',
  merges: 'Customers: CustomerKey, CustomerName, Region',
  params: 'ServerName = "sql-prod.contoso.com"\nDatabaseName = "SalesDW"',
  culture: '', makeParams: true,
  reply: [
    '@@@ QUERY @@@',
    'let',
    '    Source = Sql.Database(ServerName, DatabaseName),',
    '    Lines = Source{[Schema = "dbo", Item = "vSalesLines"]}[Data],',
    '    // Filter at the source so the database does the work',
    '    Recent = Table.SelectRows(Lines, each [OrderDate] >= #date(2023, 1, 1) and [Status] <> "Cancelled"),',
    '    Kept = Table.SelectColumns(',
    '        Recent,',
    '        {"OrderNumber", "OrderDate", "CustomerKey", "ProductKey", "Quantity", "NetAmount"}',
    '    ),',
    '    Typed = Table.TransformColumnTypes(',
    '        Kept,',
    '        {',
    '            {"OrderNumber", type text},',
    '            {"OrderDate", type date},',
    '            {"CustomerKey", Int64.Type},',
    '            {"ProductKey", Int64.Type},',
    '            {"Quantity", Int64.Type},',
    '            {"NetAmount", Currency.Type}',
    '        }',
    '    ),',
    '    WithYear = Table.AddColumn(Typed, "Year", each Date.Year([OrderDate]), Int64.Type),',
    '    Joined = Table.NestedJoin(WithYear, {"CustomerKey"}, Customers, {"CustomerKey"}, "Customer", JoinKind.LeftOuter),',
    '    Expanded = Table.ExpandTableColumn(Joined, "Customer", {"Region"})',
    'in',
    '    Expanded',
    '@@@ END @@@',
    '@@@ STEPS @@@',
    'Source: Connects to the data warehouse through the server and database parameters.',
    'Lines: Opens the sales lines view.',
    'Recent: Keeps orders from 2023 onwards that aren’t cancelled.',
    'Kept: Keeps only the six columns the model needs.',
    'Typed: Sets the type of every kept column.',
    'WithYear: Adds the order year as a whole number.',
    'Joined: Looks up each order’s customer in the Customers query.',
    'Expanded: Brings in the customer’s region.',
    '@@@ END @@@',
    '@@@ PARAMETERS @@@',
    'Name | Type | Value',
    '@@@ END @@@',
    '@@@ QUESTIONS @@@',
    'Should orders with no matching customer be kept? The merge keeps them with an empty region.',
    '@@@ END @@@'
  ].join('\n')
};
